name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "10 0 * * *"

jobs:
  build:
    strategy:
      matrix:
        versions:
          - node: 14-buster-slim
            purescript: "0.13.8"
            spago: "0.15.3"

          # Run the tests with latest versions too, since purescript and spago
          # are not stable.
          - node: latest
            purescript: latest
            spago: latest
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run tests with pinned dependency versions and latest versions
      run: |
        docker build \
          --pull \
          --build-arg NODE_TAG=${{ matrix.versions.node }} \
          --build-arg PURESCRIPT_VER=${{ matrix.versions.purescript }} \
          --build-arg SPAGO_VER=${{ matrix.versions.spago }} \
          -t hetu \
          .
        docker run --rm hetu
